---
title: epiTAD
author:
  - Jordan Creed
  - Travis Gerke
date: '2018-01-05'
slug: epitad
categories:
  - Shiny
tags: []
description: Visualize Hi-C data alongside annotation relevant to genetic epidemiology studies
weight: 30
toc: FALSE
callout: |
  Visualize Hi-C data alongside annotation relevant to genetic epidemiology studies
header_buttons:
  - text: "Run Demo App"
    url: 'https://apps.gerkelab.com/epiTAD'
    icon: "fas fa-rocket"
    class: "primary"
  - text: "View Source on GitHub"
    url: 'https://github.com/GerkeLab/epiTAD'
    icon: "fab fa-github"
    class: "secondary"
  - text: "Docker Hub"
    url: "https://hub.docker.com/r/gerkelab/epitad"
    icon: "fab fa-docker"
    class: "info"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- Project Description or README Goes Here -->


```{r echo=FALSE}
readme <- readLines(url("https://raw.githubusercontent.com/GerkeLab/epiTAD/master/README.md"))

readme <- readme[-1:-grep("<!-- README start -->", readme, fixed = TRUE)]
```

`r paste(knitr::knit(text = readme), collapse = "\n")`

